#!/usr/bin/env/ python3

import os
import subprocess
import argparse
import shlex
import re


def run_process(cmd):
    proc = subprocess.Popen(
        shlex.split(cmd),
        stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    for line in iter(proc.stdout.readline, b''):
        print(line.rstrip().decode("utf8"))


def groconvert(parmfile, coordfile):
    cmd = f"acpype.py -p {parmfile} -x {coordfile}"
    run_process(cmd)
    # Remove test files generated by acpype.py
    os.remove("em.mdp")
    os.remove("md.mdp")
    # Rename generate files
    pname, _ = os.path.splitext(args.parm)
    xname, _ = os.path.splitext(args.coord)
    os.rename(f"{pname}_GMX.top", f"{pname}.top")
    os.rename(f"{xname}_GMX.gro", f"{xname}.gro")
    # Fix charge
    with open(f"{pname}.top") as f:
        lines = f.readlines()
    ab_block = [
        i for i, line in enumerate(lines) if re.match(r"\[\s+(atoms|bonds)\s+\]", line)]
    atoms = lines[ab_block[0]:ab_block[1]]
    atoms = [line.replace(line[41:47], line[41:46]) for line in atoms]
    trun = lines[:ab_block[0]]
    trun = trun + atoms + lines[ab_block[1]:]
    with open(f"{pname}.top", "w") as f:
        f.write("".join(trun))


if __name__ == "__main__":

    parser = argparse.ArgumentParser()
    parser.add_argument('-p', '--parm', help='Amber parameter file (.parm)')
    parser.add_argument('-x', '--coord', help='Amber restart file (.rst)')
    args = parser.parse_args()
    groconvert(args.parm, args.coord)
